using System;
using System.IO;
using System.Collections.Generic;

namespace KalamaPona {
    class Program {
        static void Main(string[] args) {
            TtetScale cMajor = new TtetScale(new float[] {60, 62, 64, 65, 67, 69, 71});
            MusicCreator musicCreator = new MusicCreator();
            //musicCreator.soundCreator.BaseVolume = 0.2f;
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-14), 4.0f, 0.7f), 0.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-16), 4.0f, 0.7f), 4.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-17), 4.0f, 0.7f), 8.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-18), 4.0f, 0.7f), 12.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-14), 4.0f, 0.7f), 16.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-16), 4.0f, 0.7f), 20.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-17), 4.0f, 0.7f), 24.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-18), 4.0f, 0.7f), 28.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-14), 4.0f, 0.7f), 32.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-16), 4.0f, 0.7f), 36.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-17), 4.0f, 0.7f), 40.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-18), 4.0f, 0.7f), 44.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-14), 4.0f, 0.7f), 48.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-16), 4.0f, 0.7f), 52.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-17), 4.0f, 0.7f), 56.0f);
            musicCreator.AddWaveAt(musicCreator.CreateBassNote(cMajor.Note(-18), 4.0f, 0.7f), 60.0f);
            List<float> arpeggio1 = new List<float> ();
            arpeggio1.AddRange(musicCreator.CreateSynthNote(cMajor.Note(0), 0.5f));
            arpeggio1.AddRange(musicCreator.CreateSynthNote(cMajor.Note(1), 0.5f));
            arpeggio1.AddRange(musicCreator.CreateSynthNote(cMajor.Note(2), 0.5f));
            arpeggio1.AddRange(musicCreator.CreateSynthNote(cMajor.Note(0), 0.5f));
            arpeggio1.AddRange(musicCreator.CreateSynthNote(cMajor.Note(3), 0.5f));
            arpeggio1.AddRange(musicCreator.CreateSynthNote(cMajor.Note(4), 0.5f));
            arpeggio1.AddRange(musicCreator.CreateSynthNote(cMajor.Note(0), 0.5f));
            arpeggio1.AddRange(musicCreator.CreateSynthNote(cMajor.Note(0), 0.5f));
            List<float> arpeggio2 = new List<float> ();
            arpeggio2.AddRange(musicCreator.CreateSynthNote(cMajor.Note(0), 0.5f));
            arpeggio2.AddRange(musicCreator.CreateSynthNote(cMajor.Note(1), 0.5f));
            arpeggio2.AddRange(musicCreator.CreateSynthNote(cMajor.Note(2), 0.5f));
            arpeggio2.AddRange(musicCreator.CreateSynthNote(cMajor.Note(0), 0.5f));
            arpeggio2.AddRange(musicCreator.CreateSynthNote(cMajor.Note(4), 0.5f));
            arpeggio2.AddRange(musicCreator.CreateSynthNote(cMajor.Note(2), 0.5f));
            arpeggio2.AddRange(musicCreator.CreateSynthNote(cMajor.Note(5), 0.5f));
            arpeggio2.AddRange(musicCreator.CreateSynthNote(cMajor.Note(0), 0.5f));
            List<float> arpeggio3 = new List<float> ();
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(10), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(11), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(12), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(13), 1.0f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(12), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(13), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(14), 1.0f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(11), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(10), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(9), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(12), 1f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(14), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(15), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(13), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(14), 1f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(13), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(8), 1f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(9), 1f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(13), 1.0f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(12), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(13), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(14), 1.0f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(11), 0.5f));
            arpeggio3.AddRange(musicCreator.CreateSynthNote(cMajor.Note(10), 0.5f));
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 0.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 4.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 8.0f);
            musicCreator.AddWaveAt(arpeggio2.ToArray(), 12.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 16.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 20.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 24.0f);
            musicCreator.AddWaveAt(arpeggio2.ToArray(), 28.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 32.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 36.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 40.0f);
            musicCreator.AddWaveAt(arpeggio2.ToArray(), 44.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 48.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 52.0f);
            musicCreator.AddWaveAt(arpeggio1.ToArray(), 56.0f);
            musicCreator.AddWaveAt(arpeggio2.ToArray(), 60.0f);
            musicCreator.AddWaveAt(arpeggio3.ToArray(), 32.0f);
            musicCreator.AddWaveAt(arpeggio3.ToArray(), 48.0f);
            musicCreator.AddWaveAt(musicCreator.CreateRest(1.0f), 64.0f);
            musicCreator.soundCreator.CreateSoundBinFile(musicCreator.ResultWave.ToArray(), "output.bin");
            SoundPlayer soundPlayer = new SoundPlayer();
            soundPlayer.PlaySoundBinFile("output.bin");
            //soundPlayer.CreateWavFromSoundBinFile("output.bin", "output.wav");
        }
    }
}
